apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld-ilb
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "ILBSubnet"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: aks-helloworld-app